apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-ia-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curso-ia
  template:
    metadata:
      labels:
        app: curso-ia
    spec:
      containers:
      - name: curso-ia
        image: acrhsouzalab02.azurecr.io/landingpage/curso-ia:latest
        ports:
        - containerPort: 80
